---
dist: xenial
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'

cache:
  pip: true
  directories:
    - eggs/

before_install:
  - pip install -r requirements.txt

install:
  - buildout -c buildout-travis.cfg

script:
  - bin/test

notifications:
  email:
    on_success: never
    on_failure: never
